name: Test

on: [push]

env:
  DEVELOPER_DIR: /Applications/Xcode_13.4.app

jobs:
  ci:
    runs-on: macOS-12
    timeout-minutes: 60
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Cache BuildTools
      id: cache-buildtools
      uses: actions/cache@v2
      with:
        path: '**/.build'
        key: ${{ runner.os }}-spm-build-${{ hashFiles('**/Package.resolved', 'Makefile') }}
        restore-keys: |
          ${{ runner.os }}-spm-build
    - name: Test
      run: make test
    - uses: kishikawakatsumi/xcresulttool@v1.4.0
      with:
        path: .build/TestResults.xcresult
        show-code-coverage: true
      if: success() || failure()